
### Variables
@baseUrl = http://localhost:6101
@userId = 533e9294-76cf-41eb-9e2a-19064f7875e2
@clientId = b9794d29-c2a2-47f5-9ed2-a9821b4a92a7
@authCode = pH96AUp7XqXTpl7qEMN0f5d82448QqFfdgO4dC97gXjeLhthv7IgqQZvXBNNkW5n
@AccessToken = 
@RefreshToken = 

### healthchecker
GET {{baseUrl}}/healthchecker

### Swagger UI
GET {{baseUrl}}/swagger-ui/

### Login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "demo3",
    "pwd": "welcome_"
}


### Register
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "nghia123456"
}

### Change Profile
POST {{baseUrl}}/profile/af6fea24-65e0-4940-a7d9-4f5b1d1d5ab9
Content-Type: application/json

{
    "first_name": "NGHIA",
    "last_name": "NGUYEN",
    "last_name1": "NGUYEN LongTextLongText"
}


### Register 
POST {{baseUrl}}/register
Content-Type: application/json

{
    "email": "test_n2",
    "password": "Pass@wor1",
    "first_name": "Abc002",
    "last_name": "Xyz002"
}

### Delete User
DELETE {{baseUrl}}/users/53af92fc-ba07-45dc-949e-60ae55316e71
Content-Type: application/json

### Get User
GET {{baseUrl}}/users/533e9294-76cf-41eb-9e2a-19064f7875e2
Content-Type: application/json

### Finds User
GET {{baseUrl}}/users?page_size=1&page=4&first_name=li|nghia_like&last_name=eq|nghia_equal&age=lte|12&email=eq|nghia@test.com&id=eq|4df3f7dd-e618-4254-9330-f1d9aa65f129
Content-Type: application/json

### Finds User
GET {{baseUrl}}/users?page_size=10&page=1&&order_name=first_name&order_direction=-1
Content-Type: application/json

### Finds User in id array
GET {{baseUrl}}/users?page_size=10&page=1&id=in|c8b35d43-a7aa-4aa7-bf7d-011ab2c76461,4df3f7dd-e618-4254-9330-f1d9aa65f129
Content-Type: application/json

### Get Test Users 
GET {{baseUrl}}/test_users
Content-Type: application/json

### Get All Roles
GET {{baseUrl}}/roles
Content-Type: application/json


### Logout
POST {{baseUrl}}/logout
Content-Type: application/json


### --------- CLIENT

### Get Client
GET {{baseUrl}}/clients/{{clientId}}
Content-Type: application/json

### Filter Client
GET {{baseUrl}}/clients?client_secret=li|sec&allowed_grants=in|type2,type12
Content-Type: application/json

### Filter Client
GET {{baseUrl}}/clients?sec&allowed_grants=nin|auth_code
Content-Type: application/json

### TOKEN

### Create new token
# @name tokenRequest
POST {{baseUrl}}/oauth/token
Content-Type: application/json

{   
    "client_id": "{{clientId}}",
    "code": "{{authCode}}",
    "grant_type": "authorization_code"
}

@AccessToken = {{tokenRequest.response.body.data.access_token}}
@RefreshToken = {{tokenRequest.response.body.data.refresh_token}}


### Create new token from refresh token
POST {{baseUrl}}/oauth/token
Content-Type: application/json

{   
    "client_id": "{{clientId}}",
    "code": "{{RefreshToken}}",
    "grant_type": "refresh_token"
}

