
### Variables
@baseUrl = http://localhost:5011
# @baseUrl = http://localhost:6101
@userId = a8cf9071-4c48-46cf-a3c7-8acb0bfeb757
@clientId = 5ed8e536-12ae-463d-ae9b-8c78cc5481e1
# @authCode = 
@AccessToken = 
@RefreshToken = 

@userEmail = nghiandd@gmail.com
@userPassword = Test@123456

### healthchecker
GET {{baseUrl}}/healthchecker

### Swagger UI
GET {{baseUrl}}/swagger-ui/



### Register 
# @ prompt userEmail User email
# @ prompt userPassword Password
POST {{baseUrl}}/register
Content-Type: application/json

{
    "email": "{{userEmail}}",
    "password": "{{userPassword}}",
    "first_name": "Nghia",
    "last_name": "Nguyen"
}


### Request Authentication
# @name authenticationRequest
POST {{baseUrl}}/public/requests/code
Content-Type: application/json

{
    "client_id": "{{clientId}}",
    "scopes": ["email", "profile"],
    "redirect_uri": "http://localhost:8081/auth_result",
    "response_type": "code",
    "state": "eyJmaW5nZXJwcmludCI6Ik15UHJpbmdlcnByaW50IiwidGltZXN0YW1wIjoxNzYxODc5MzEwNzU5fQ=="
}

### Request Login
# @name authLoginRequest
POST {{baseUrl}}/requests/login
Content-Type: application/json

{
  "email": "{{userEmail}}",
  "password": "{{userPassword}}",
  "state": "b40f3665-7bc4-42c4-bfcf-41e32fc127a7"
}



### Request Register
# @name authRegisterRequest
POST {{baseUrl}}/requests/register
Content-Type: application/json

{
  "email": "{{userEmail}}",
  "password": "{{userPassword}}",
  "state": "b40f3665-7bc4-42c4-bfcf-41e32fc127a7"
}



### Login
# @ prompt userEmail User email
# @ prompt userPassword User email
# @name loginRequest
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "{{userEmail}}1",
    "password": "{{userPassword}}",
    "client_id": "{{clientId}}",
    "scopes": ["scope1", "scope2"],
    "redirect_uri": "http://localhost:4200"
}


@authCode = {{loginRequest.response.body.data.code}}


### Change Profile
POST {{baseUrl}}/profile/af6fea24-65e0-4940-a7d9-4f5b1d1d5ab9
Content-Type: application/json

{
    "first_name": "NGHIA",
    "last_name": "NGUYEN",
    "last_name1": "NGUYEN LongTextLongText"
}


### Delete User
DELETE {{baseUrl}}/users/{{userId}}
Content-Type: application/json

### Get User
GET {{baseUrl}}/users/{{userId}}
Content-Type: application/json

### Finds User
GET {{baseUrl}}/users?page_size=1&page=4&first_name=li|nghia_like&last_name=eq|nghia_equal&age=lte|12&email=eq|nghia@test.com&id=eq|4df3f7dd-e618-4254-9330-f1d9aa65f129
Content-Type: application/json

### Finds User
GET {{baseUrl}}/users?page_size=10&page=1&&order_name=first_name&order_direction=-1
Content-Type: application/json

### healthchecker
GET {{baseUrl}}/healthchecker
Content-Type: application/json
tracestate: 00-6eac2b714dd57b47498837ce4b023876-c8e10305886ac80f-01


### Finds User in id array
GET {{baseUrl}}/users?page_size=10&page=1&id=in|{{userId}},4df3f7dd-e618-4254-9330-f1d9aa65f129
Content-Type: application/json

### Get Test Users 
GET {{baseUrl}}/test_users
Content-Type: application/json

### ROLES
@roleId = b3298a2b-3a6d-40e3-8938-d4c213c589d3
### Role
POST {{baseUrl}}/roles
Content-Type: application/json

{
  "client_id": "{{clientId}}",
  "description": "DNAPP Guest",
  "name": "DNAPP_GUEST"
}

### Get All Roles
GET {{baseUrl}}/roles?page=0&page_size=10
Content-Type: application/json

### Get All Roles with permissions
GET {{baseUrl}}/roles?includes=permissions
Content-Type: application/json


### Search Roles by permissions[resource]
GET {{baseUrl}}/roles?permissions[resource]=sw|LOOKUP
Content-Type: application/json

### Get All Roles with permissions filtered by resource
GET {{baseUrl}}/roles?includes=permissions&permissions[resource]=sw|LOOKUP
Content-Type: application/json

### Get Role by Id
GET {{baseUrl}}/roles/{{roleId}}?includes=permissions
Content-Type: application/json

### PERMISSIONS

@permissionId = 8d02cb6f-54f7-4f26-a88d-c35127850c03

### Create Permission
POST {{baseUrl}}/permissions
Content-Type: application/json

{
  "resource": "AUTH_MANAGE_USERS",
  "description": "Manage users in auth service",
  "mask": 1
}

### Get Permission by Id
GET {{baseUrl}}/permissions/{{permissionId}}
Content-Type: application/json

### Update Permission
PATCH {{baseUrl}}/permissions/{{permissionId}}
Content-Type: application/json

{
  "resource": "AUTH_MANAGE_USERS",
  "description": "Manage users in auth service (updated)",
  "mask": 3
}

### Delete Permission
DELETE {{baseUrl}}/permissions/2fd08099-b0da-40aa-a3ff-eb2c643df3db
Content-Type: application/json

### Filter Permissions
GET {{baseUrl}}/permissions?page=1&page_size=20
Content-Type: application/json

### Filter Permissions by resource
GET {{baseUrl}}/permissions?resource=sw|AUTH&page=1&page_size=20
Content-Type: application/json

### Assign Permissions to Role
POST {{baseUrl}}/roles/{{roleId}}/assign-permissions
Content-Type: application/json

{
  "permission_ids": ["{{permissionId}}"]
}

### Unassign Permissions from Role
POST {{baseUrl}}/roles/{{roleId}}/unassign-permissions
Content-Type: application/json

{
  "permission_ids": ["{{permissionId}}"]
}

### Get Permissions by Role
GET {{baseUrl}}/roles/{{roleId}}/permissions
Content-Type: application/json


### Logout
POST {{baseUrl}}/logout
Content-Type: application/json


### --------- CLIENT

### Get Client
POST {{baseUrl}}/clients
Content-Type: application/json

{
  "allowed_grants": [
    "email",
    "profile"
  ],
  "client_secret": "DN-MS-Test-Secret-Code",
  "client_key": "DNAPP",
  "description": "DN App Description",
  "name": "DN App",
  "redirect_uris": [
    "http://localhost:80801"
  ]
}

### Get Client
GET {{baseUrl}}/clients/{{clientId}}
Content-Type: application/json

### Filter Client
GET {{baseUrl}}/clients?client_secret=li|sec&allowed_grants=in|type2,type12
Content-Type: application/json

### Filter Client
GET {{baseUrl}}/clients?sec&allowed_grants=nin|auth_code
Content-Type: application/json

### TOKEN

### Create new token
# @name tokenRequest
POST {{baseUrl}}/tokens/oauth
Content-Type: application/json

{   
    "client_id": "{{clientId}}",
    "code": "{{authCode}}",
    "grant_type": "authorization_code"
}

@AccessToken = {{tokenRequest.response.body.data.access_token}}
@RefreshToken = {{tokenRequest.response.body.data.refresh_token}}


### Create new token from refresh token
# @name refreshRequest
POST {{baseUrl}}/tokens/oauth
Content-Type: application/json

{   
    "client_id": "{{clientId}}",
    "code": "{{RefreshToken}}",
    "grant_type": "refresh_token"
}

@AccessToken1 = {{refreshRequest.response.body.data.access_token}}
@RefreshToken1 = {{refreshRequest.response.body.data.refresh_token}}
###


### Verify access token
# @name verifyTokenRequest
POST {{baseUrl}}/tokens/verify
Content-Type: application/json

{   
    "client_id": "{{clientId}}",
    "token": "{{AccessToken}}"
}



### Test
GET {{baseUrl}}/permissions?resource=sw|LOOKUP&page=1&page_size=20
Content-Type: application/json

### GET PERMISION of Service AUTH
GET {{baseUrl}}/permissions?resource=sw|AUTH&page=1&page_size=20
Content-Type: application/json
baggage: accesses=ADMIN_ALL*,user_id=00000000-0000-0000-0000-000000000000,client_id=00000000-0000-0000-0000-000000000000