@baseUrl = http://localhost:5141
@feeConfigId = a21020c6-1496-467c-ad69-e1b352c6338c

### healthchecker
GET {{baseUrl}}/healthchecker

### Swagger UI
GET {{baseUrl}}/swagger-ui/

### ===== FEE CONFIGURATIONS =====

### Get All Fee Configurations
GET {{baseUrl}}/fee-configurations


### Search Fee
GET {{baseUrl}}/fee-configurations?percentage_rate=gt|3


### Create Fee Configuration
POST {{baseUrl}}/fee-configurations
Content-Type: application/json

{
  "effective_from": "2023-01-01T00:00:00",
  "fixed_amount": 0.2,
  "max_fee": 100.6,
  "merchant_id": "mch_123456789",
  "min_fee": 0.4,
  "percentage_rate": 2.5,
  "pricing_model": "PERCENTAGE"
}

### Get Fee Configuration By ID
GET {{baseUrl}}/fee-configurations/{{feeConfigId}}

### Update Fee Configuration
PATCH {{baseUrl}}/fee-configurations/{{feeConfigId}}
Content-Type: application/json

{
  "percentage_rate": 3.33,
  "tier_config": {
    "field1": 232,
    "field2": "data 2",
    "field3": {
      "f3_a": {
        "a1": "f3_a1_1",
        "a2": "f3_a1_2"
      }
    }
  }
}

### Delete Fee Configuration
DELETE {{baseUrl}}/fee-configurations/d63de457-d2de-49ed-ba98-017b49afd515