@baseUrl = http://localhost:5131
@merchantId = mch_7993b79cadbc4612

### healthchecker
GET {{baseUrl}}/healthchecker

### Swagger UI
GET {{baseUrl}}/swagger-ui/

### ===== MERCHANT =====

### Get All Merchants
GET {{baseUrl}}/merchants

### Search Merchants
GET {{baseUrl}}/merchants?status=li|INACTIVE&order_name=business_name&order_direction=1

### Create Merchant
POST {{baseUrl}}/merchants
Content-Type: application/json

{
  "business_name": "Acme Corp",
  "email": "contact@acme.example",
  "phone": "1234567890",
  "business_type": "COMPANY",
  "kyc_status": "PENDING",
  "status": "ACTIVE"
}

### Get Merchant By ID
GET {{baseUrl}}/merchants/{{merchantId}}

### Update Merchant
PATCH {{baseUrl}}/merchants/{{merchantId}}
Content-Type: application/json

{
  "business_name": "Acme Corp Updated",
  "status": "INACTIVE"
}

### Delete Merchant
DELETE {{baseUrl}}/merchants/mch_2c60d3fe5aeb4736
