@baseUrl = http://localhost:5131
@merchantId = mch_7993b79cadbc4612

### healthchecker
GET {{baseUrl}}/healthchecker

### Swagger UI
GET {{baseUrl}}/swagger-ui/

### ===== MERCHANT =====

### Get All Merchants
GET {{baseUrl}}/merchants

### Search Merchants
GET {{baseUrl}}/merchants?status=li|INACTIVE&order_name=business_name&order_direction=1

### Create Merchant
POST {{baseUrl}}/merchants
Content-Type: application/json

{
  "business_name": "Acme Corp",
  "email": "contact@acme.example",
  "phone": "1234567890",
  "business_type": "COMPANY",
  "kyc_status": "PENDING",
  "status": "ACTIVE"
}

### Get Merchant By ID
GET {{baseUrl}}/merchants/{{merchantId}}

### Get API Keys by Merchant
GET {{baseUrl}}/merchants/{{merchantId}}/api-keys

### Update Merchant
PATCH {{baseUrl}}/merchants/{{merchantId}}
Content-Type: application/json

{
  "business_name": "Acme Corp Updated",
  "status": "INACTIVE"
}

### Delete Merchant
DELETE {{baseUrl}}/merchants/mch_2c60d3fe5aeb4736

### ===== API KEYS =====

### Create API Key
POST {{baseUrl}}/api-keys
Content-Type: application/json

{
  "environment": "production",
  "api_key": "my-secret-api-key-value",
  "merchant_id": "{{merchantId}}"
}

### Get API Key By ID
@apiKeyId = 1
GET {{baseUrl}}/api-keys/{{apiKeyId}}



### Get API Keys (filter/pagination)
GET {{baseUrl}}/api-keys?page=1&size=20&order_name=created_at&order_direction=1

### Update API Key
PATCH {{baseUrl}}/api-keys/{{apiKeyId}}
Content-Type: application/json

{
  "environment": "staging",
  "api_key": "my-updated-api-key-value"
}

### Delete API Key
DELETE {{baseUrl}}/api-keys/2

### ===== WEBHOOKS =====

@webhookId = a14ef300-5f23-4cd3-b424-f63ce27276f1

### Get Webhooks 
GET {{baseUrl}}/webhooks

### Create Webhook
POST {{baseUrl}}/webhooks
Content-Type: application/json

{
  "merchant_id": "{{merchantId}}",
  "url": "https://example.com/webhook",
  "event_types": ["payment_succeeded", "payment_failed"],
  "secret": "webhook-secret-key",
  "status": "ACTIVE"
}

### Get Webhook By ID
GET {{baseUrl}}/webhooks/{{webhookId}}

### Get Webhooks (filter/pagination)
GET {{baseUrl}}/webhooks?page=1&size=20&order_name=created_at&order_direction=1

### Update Webhook
PATCH {{baseUrl}}/webhooks/{{webhookId}}
Content-Type: application/json

{
  "url": "https://example.com/updated-webhook",
  "event_types": ["payment_succeeded"],
  "status": "INACTIVE"
}

### Delete Webhook
DELETE {{baseUrl}}/webhooks/1ba9e455-86dd-48b4-9955-48643497085c
