[package]
name = "features-tagging-service"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "features_tagging_service"
path = "src/lib.rs"

[dependencies]
chrono = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

shared-shared-config = { workspace = true }
shared-shared-data-core = { workspace = true }
shared-shared-data-error = { workspace = true }

features-tagging-entities = { workspace = true }
features-tagging-model = { workspace = true }
features-tagging-repo = { workspace = true }
