

GET http://127.0.0.1:8080
accept: text/html
accept-encoding: gzip, deflate, br, zstd
accept-language: en-US,en;q=0.9

### Get request
GET http://127.0.0.1:8080/request?client_id=b9794d29-c2a2-47f5-9ed2-a9821b4a92a7&scope=openid+profile+email+offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A8081%2Fauth_result&response_type=code&state=eyJmaW5nZXJwcmludCI6Ik15UHJpbmdlcnByaW50IiwidGltZXN0YW1wIjoxNzYxODc5MzEwNzU5fQ%3D%3D&screen=login
accept: text/html
accept-encoding: gzip, deflate, br, zstd
accept-language: en-US,en;q=0.9

### Health
GET http://127.0.0.1:8080/health
accept-encoding: gzip, deflate, br, zstd
accept-language: en-US,en;q=0.9