daemon: false
error_log: /var/log/dn-gateway/error.log
pid_file: /var/run/dn-gateway.pid
upgrade_sock: /var/run/dn-gateway.sock
user: root
group: root
threads: 8
work_stealing: true
grace_period_seconds: 60
graceful_shutdown_timeout_seconds: 30
upstream_keepalive_pool_size: 10
upstream_connect_offload_threadpools: 2
upstream_connect_offload_thread_per_pool: 5
upstream_debug_ssl_keylog: false
gateways:
  - name: root
    bind_addresses:
      - host: 0.0.0.0
        port: 6000
      - host: 0.0.0.0
        port: 6001
      - host: 0.0.0.0
        port: 6002
    routers:
      - upstream: auth
        filter: auth_router_filter
      - upstream: app_notification
        filter: app_notification_filter
      - upstream: profile
        filter: profile_router_filter
      - upstream: translation
        filter: translation_router_filter
      - upstream: event
        filter: event_router_filter
      - upstream: inventory
        filter: inventory_router_filter
      - upstream: booking
        filter: booking_router_filter
      - upstream: bakery
        filter: bakery_router_filter
      - upstream: email_template
        filter: email_template_router_filter
      - upstream: merchant
        filter: merchant_router_filter
      - upstream: fee
        filter: fee_router_filter
      - upstream: wallet
        filter: wallet_router_filter
      - upstream: payment_core
        filter: payment_core_router_filter
      - upstream: stripe
        filter: stripe_router_filter
      - upstream: notification
        filter: notification_router_filter

    upstreams:
      - name: auth
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-auth-1
              port: 5011
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-auth-2
              port: 5012
            tls: false
            sni: null
            weight: 2

      - name: bakery
        default: false
        traffic_distribution_policy: round_robin
        upstream_nodes:
          - address:
              host: api-bakery-1
              port: 5021
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-bakery-2
              port: 5022
            tls: false
            sni: null
            weight: 2

      - name: email_template
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-email-template-1
              port: 5031
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-email-template-2
              port: 5032
            tls: false
            sni: null
            weight: 2

      - name: notification
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-notification-1
              port: 5041
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-notification-2
              port: 5042
            tls: false
            sni: null
            weight: 2

      - name: profile
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-profile-1
              port: 5051
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-profile-2
              port: 5052
            tls: false
            sni: null
            weight: 2

      - name: translation
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-translation-1
              port: 5061
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-translation-2
              port: 5062
            tls: false
            sni: null
            weight: 2

      - name: event
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-event-1
              port: 5071
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-event-2
              port: 5072
            tls: false
            sni: null
            weight: 2

      - name: inventory
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-inventory-1
              port: 5081
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-inventory-2
              port: 5082
            tls: false
            sni: null
            weight: 2

      - name: booking
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-booking-1
              port: 5091
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-booking-2
              port: 5092
            tls: false
            sni: null
            weight: 2

      - name: payment_core
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-payment-core-1
              port: 5101
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-payment-core-2
              port: 5102
            tls: false
            sni: null
            weight: 2

      - name: stripe
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-stripe-1
              port: 5121
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-stripe-2
              port: 5122
            tls: false
            sni: null
            weight: 2

      - name: merchant
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-merchant-1
              port: 5131
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-merchant-2
              port: 5132
            tls: false
            sni: null
            weight: 2

      - name: fee
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-fee-1
              port: 5141
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-fee-2
              port: 5142
            tls: false
            sni: null
            weight: 2

      - name: wallet
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: api-wallet-1
              port: 5151
            tls: false
            sni: null
            weight: 1
          - address:
              host: api-wallet-2
              port: 5152
            tls: false
            sni: null
            weight: 2

      - name: app_notification
        default: false
        traffic_distribution_policy: random
        upstream_nodes:
          - address:
              host: app-notification-1
              port: 4001
            tls: false
            sni: null
            weight: 1
          - address:
              host: app-notification-2
              port: 4002
            tls: false
            sni: null
            weight: 1

    interceptors:
      # Auth
      - name: auth_request_id
        type: request_id
        enabled: true
        filter: auth_router_filter
      - name: auth_cors
        type: cors
        enabled: true
        filter: auth_router_filter
        config:
          allowed_domains: localhost
      - name: auth_token_auth
        type: token_auth
        enabled: true
        filter: auth_router_filter
        config:
          use_auth_service: true
      - name: auth_rate_limiter
        type: rate_limiter
        enabled: true
        filter: auth_router_filter
        config:
          capacity: 5
          refill_rate: 2
          refill_interval: 10

      # Bakery
      - name: bakery_request_id
        type: request_id
        enabled: true
        filter: bakery_router_filter
      - name: bakery_token_auth
        type: token_auth
        enabled: true
        filter: bakery_router_filter
        config:
          use_auth_service: true
      - name: bakery_cors
        type: cors
        enabled: true
        filter: bakery_router_filter
        config:
          allowed_domains: localhost
      - name: bakery_rate_limiter
        type: rate_limiter
        enabled: true
        filter: bakery_router_filter
        config:
          capacity: 5
          refill_rate: 2
          refill_interval: 10

      # Profile
      - name: profile_cors
        type: cors
        enabled: true
        filter: profile_router_filter
        config:
          allowed_domains: localhost

      # Translation
      - name: translation_cors
        type: cors
        enabled: true
        filter: translation_router_filter
        config:
          allowed_domains: localhost

      # Event
      - name: event_cors
        type: cors
        enabled: true
        filter: event_router_filter
        config:
          allowed_domains: localhost

      # Inventory
      - name: inventory_cors
        type: cors
        enabled: true
        filter: inventory_router_filter
        config:
          allowed_domains: localhost

      # Booking
      - name: booking_cors
        type: cors
        enabled: true
        filter: booking_router_filter
        config:
          allowed_domains: localhost

      # Email Template
      - name: email_template_cors
        type: cors
        enabled: true
        filter: email_template_router_filter
        config:
          allowed_domains: localhost

      # Merchant
      - name: merchant_cors
        type: cors
        enabled: true
        filter: merchant_router_filter
        config:
          allowed_domains: localhost

      # Fee
      - name: fee_cors
        type: cors
        enabled: true
        filter: fee_router_filter
        config:
          allowed_domains: localhost

      # Wallet
      - name: wallet_cors
        type: cors
        enabled: true
        filter: wallet_router_filter
        config:
          allowed_domains: localhost

      # Payment Core
      - name: payment_core_cors
        type: cors
        enabled: true
        filter: payment_core_router_filter
        config:
          allowed_domains: localhost

      # Stripe
      - name: stripe_cors
        type: cors
        enabled: true
        filter: stripe_router_filter
        config:
          allowed_domains: localhost

      # Notification
      - name: notification_cors
        type: cors
        enabled: true
        filter: notification_router_filter
        config:
          allowed_domains: localhost

      # App Notification
      - name: app_notification_request_id
        type: request_id
        enabled: true
        filter: app_notification_filter

    filters:
      - name: auth_router_filter
        path:
          operator: start_with
          value: /api/auth
      - name: app_notification_filter
        path:
          operator: start_with
          value: /app-notification
        timeout: 100
      - name: profile_router_filter
        path:
          operator: start_with
          value: /api/profile
      - name: translation_router_filter
        path:
          operator: start_with
          value: /api/translation
      - name: event_router_filter
        path:
          operator: start_with
          value: /api/event
      - name: inventory_router_filter
        path:
          operator: start_with
          value: /api/inventory
      - name: booking_router_filter
        path:
          operator: start_with
          value: /api/booking
      - name: bakery_router_filter
        path:
          operator: start_with
          value: /api/bakery
      - name: email_template_router_filter
        path:
          operator: start_with
          value: /api/email-template
      - name: merchant_router_filter
        path:
          operator: start_with
          value: /api/merchant
      - name: fee_router_filter
        path:
          operator: start_with
          value: /api/fee
      - name: wallet_router_filter
        path:
          operator: start_with
          value: /api/wallet
      - name: payment_core_router_filter
        path:
          operator: start_with
          value: /api/payment-core
      - name: stripe_router_filter
        path:
          operator: start_with
          value: /api/stripe
      - name: notification_router_filter
        path:
          operator: start_with
          value: /api/notification
