
### Variables
@baseUrl = http://localhost:6001
@userId = 3158787f-7b76-4b04-b79d-4d8fac17d841
@clientId = b9794d29-c2a2-47f5-9ed2-a9821b4a92a7

@acessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJkbl9kYXRhIjp7InVzZXJfaWQiOiIwNjZkZjdiMC1kY2QxLTRlN2MtOTRhMS05YjVmNjg3OTRjYTciLCJhY2Nlc3NlcyI6W3sicm9sZV9uYW1lIjoiRE5BUFBfR1VFU1QiLCJrZXkiOiJhY2Nlc3Nfa2V5In1dfSwiZXhwIjoxNzY3ODU5ODAzLCJpYXQiOjE3Njc3NzM0MDMsImp0aSI6ImY2MjVkZWZkLTZhNDEtNGNjMC1hMjQ0LTdjNTIzMjg0ODliNCJ9.lmeHjTnHe83MrRA4wVyj0lL3MqvsbGyY76C8C1IFOuE

### 

GET {{baseUrl}}/api/bakery/bakeries
Content-Type: application/json

###
tracestate: congo=t61rcWkgMzE,rojo=00f067aa0ba902b7
traceparent: 00-4bf92f3577b34da6a3ce929d0e0e4731-00f067aa0ba902b1-01

###



###
GET {{baseUrl}}/api/bakery/bakeries/1?param_1=one
Content-Type: application/json

###
GET {{baseUrl}}/api/bakery/bakeries/2
Content-Type: application/json
Authorization: Bearer {{acessToken}}

# AUTH
### Generate token
# @name generateRequest
POST {{baseUrl}}/api/auth/oauth/token
Content-Type: application/json

{
    "client_id":"5ed8e536-12ae-463d-ae9b-8c78cc5481e1",
    "grant_type":"authorization_code",
    "code":"t6Ovvp4ZtH9b619DrrAti0xDIHwbd6dzKV9LfezX7AgxZNCcDu21IArvirSqzKO5"
}
@AccessToken = {{generateRequest.response.body.data.access_token}}



### Verify tokein
POST {{baseUrl}}/api/auth/tokens/verify
Content-Type: application/json

{
    "client_id":"5ed8e536-12ae-463d-ae9b-8c78cc5481e1",
    "token": "{{acessToken}}"
}

