
### Variables
@baseUrl = http://localhost:6101
@userId = 3158787f-7b76-4b04-b79d-4d8fac17d841

@templateId = 1
@tempalateTranslationId = 1
@placeholderId = 1

### healthchecker
GET {{baseUrl}}/healthchecker

### Swagger UI
GET {{baseUrl}}/swagger-ui/

### Email Template API

### Insert Email Template 
POST {{baseUrl}}/email-templates
Content-Type: application/json
dn_user_id: {{userId}}

{
    "name": "Email Template Name",
    "description": "Template Description for testing"
}


### Get Email Template 
GET {{baseUrl}}/email-templates/{{templateId}}
Content-Type: application/json

### Filter Email Template 
GET {{baseUrl}}/email-templates?description=li|testing&name=li|Name
Content-Type: application/json


### Delete Email Template 
DELETE {{baseUrl}}/email-templates/2
Content-Type: application/json

### Template Translation API

### Insert Template Translation
POST {{baseUrl}}/template-translations 
Content-Type: application/json

{
  "body": "Template Translation Body EN",
  "language_code": "en",
  "subject": "Template Translation Subject EN",
  "template_id": {{templateId}},
  "version_name": "1.0.0"
}


### Get Template Translation 
GET {{baseUrl}}/template-translations/{{tempalateTranslationId}}
Content-Type: application/json


### Filter Template Translation 
GET {{baseUrl}}/template-translations?body=li|Body&template_id=eq|1
Content-Type: application/json


### Update Template Translation 
PATCH {{baseUrl}}/template-translations/{{tempalateTranslationId}}
Content-Type: application/json

{
  "body": "Template Translation Body EN Update"
}

### DELETE Template Translation 
DELETE {{baseUrl}}/template-translations/4
Content-Type: application/json


### Template Placeholder API

### Insert Template Placeholder
POST {{baseUrl}}/template-placeholders 
Content-Type: application/json

{
  "description": "placeholder description",
  "example_value": "placeholder example value",
  "is_required": true,
  "placeholder_key": "placeholder_key",
  "template_id": {{templateId}}
}


### Delete Template Placeholder
# @prompt deletePlaceholderId Delete Placeholder Id
DELETE {{baseUrl}}/template-placeholders/{{deletePlaceholderId}}
Content-Type: application/json

### Filter Template Placeholder
GET {{baseUrl}}/template-placeholders/{{placeholderId}}
Content-Type: application/json

### Filter Template Placeholder
GET {{baseUrl}}/template-placeholders?example_value=li|value
Content-Type: application/json

### Update Template Placeholder
PATCH {{baseUrl}}/template-placeholders/{{placeholderId}}
Content-Type: application/json  

{
  "example_value": "placeholder example value update"
}